"""new changes

Revision ID: 909588b10f9f
Revises: 99d8fcdb2290
Create Date: 2023-03-16 20:30:56.882120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '909588b10f9f'
down_revision = '99d8fcdb2290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_history')
    op.drop_table('report_comments')
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))
        batch_op.drop_column('title')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.BLOB(), nullable=True))

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('description')

    op.create_table('report_comments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('reportComment', sa.VARCHAR(length=100), nullable=True),
    sa.Column('dateCommented', sa.DATETIME(), nullable=True),
    sa.Column('report_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date_created', sa.DATETIME(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=50), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
